apiVersion: v1
kind: Service
metadata:
  name: sk-team-09-frontend
  namespace: sk-team-09
  labels:
    app: sk-team-09-frontend
spec:
  type: ClusterIP
  selector:
    app: sk-team-09-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80           
      targetPort: 80     
